"""add the password field

Revision ID: 311fa7d7d56b
Revises: 227567064791
Create Date: 2024-02-13 22:43:41.769319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311fa7d7d56b'
down_revision = '227567064791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
